extends SceneTree
const SouthWalk=preload("res://themes/hoplite_south_walk.tres")
const NorthWalk=preload("res://themes/hoplite_north_walk.tres")
const SouthAttack=preload("res://themes/hoplite_south_attack.tres")
const NorthRest=preload("res://themes/hoplite_north_rest.tres")
const ThrustClip=preload("res://themes/hoplite_thrust_clip.tres")
const GuardClip=preload("res://themes/hoplite_guard_clip.tres")
const Clip=preload("res://presentation/sprite_clip.gd")
var failures:=0
var checks:=0
func check(value: bool, label: String) -> void:
	checks+=1
	if not value: failures+=1; push_error(label)
func _initialize() -> void:
	check(SouthWalk.validation_error()=="", "South stride atlas and pivots are valid")
	check(NorthWalk.validation_error()=="", "Walk source uses valid typed per-frame pivots")
	check(GuardClip is Clip and GuardClip.validation_error()=="","Shipped guard Resource loads its script, atlas and timing")
	check(ThrustClip.validation_error()=="", "Irregular thrust frame contract is valid")
	var invalid=ThrustClip.duplicate()
	invalid.frame_pivots.clear()
	check(not invalid.validation_error().is_empty(), "Unequal frames reject absent pivots")
	invalid=ThrustClip.duplicate()
	invalid.draw_scale=0.0
	check(not invalid.validation_error().is_empty(), "Reject zero art scale")
	check(SouthAttack.validation_error()=="", "South attack depth metadata is valid")
	invalid=SouthAttack.duplicate()
	invalid.depth_bias=1.0
	check(not invalid.validation_error().is_empty(), "Reject excessive sprite depth offset")
	var clip:=Clip.new()
	var img:=Image.create(64,32,false,Image.FORMAT_RGBA8)
	clip.atlas=ImageTexture.create_from_image(img)
	clip.regions=[Rect2i(0,0,32,32),Rect2i(32,0,32,32)]
	clip.durations=PackedFloat32Array([.125,.375])
	check(clip.validation_error()=="","Valid ordered clip")
	check(clip.frame_at(.124)==0 and clip.frame_at(.125)==1,"Exact frame boundary")
	check(clip.frame_at(.5)==0,"Loop boundary returns first")
	clip.looping=false
	check(clip.frame_at(9)==1,"One-shot holds final")
	check(clip.frame_at(-1)==0,"Negative time clamps")
	clip.durations[0]=0
	check(clip.frame_at(0)==-1,"Reject zero duration")
	clip.durations[0]=.125
	clip.regions[1]=Rect2i(50,0,32,32)
	check(not clip.validation_error().is_empty(),"Reject atlas overflow")
	if DisplayServer.get_name() != "headless":
		clip.regions[1]=Rect2i(32,0,32,32)
		clip.pivot=Vector2(16,30)
		var actor:=preload("res://presentation/pixel_actor.gd").new()
		check(actor.set_clip(clip),"Actor accepts valid clip")
		check(actor.offset==Vector2(0,14),"Foot pivot raises image above origin")
		actor.show_time(.125)
		check(actor.texture.region.position==Vector2(32,0),"Actor displays ordered second frame")
		var rest=clip.duplicate()
		rest.looping=true
		check(actor.reset_playback(rest),"Rest clip resets reaction state")
		check(actor.react_to_hit(7,clip),"Fresh authoritative event starts reaction")
		actor.advance_visual(.2)
		check(not actor.react_to_hit(7,clip) and actor.texture.region.position==Vector2(32,0),"Repeated snapshot does not restart reaction")
		actor.advance_visual(1)
		check(actor.clip==rest,"Completed reaction returns to rest")
		check(not actor.react_to_hit(6,clip),"Older events ignored")
		actor.reset_playback(rest)
		check(actor.react_to_hit(0,clip),"Rematch accepts new event numbering")
		check(actor.play_attack(40,ThrustClip), "Attack event starts independent action clock")
		actor.advance_visual(.2)
		check(actor.scale==Vector3.ONE*ThrustClip.draw_scale and actor.texture.region==Rect2(ThrustClip.regions[2]), "Thrust reaches authored contact frame at matching scale")
		check(not actor.play_attack(40,ThrustClip), "Repeated attack does not rewind clip")
		actor.advance_visual(1)
		check(actor.clip==rest and actor.scale==Vector3.ONE and actor.material_override==null, "Attack recovery restores rest scale and native alpha material")
		actor.reset_playback(rest)
		check(actor.play_attack(0,ThrustClip), "Rematch resets attack event numbering")
		var attack_clip=actor.clip
		check(actor.set_rest_pose(NorthRest) and actor.clip==attack_clip, "Facing change updates recovery pose without interrupting action")
		check(not actor.play_attack(0,ThrustClip), "Facing changes preserve event deduplication")
		actor.advance_visual(1)
		check(actor.clip==NorthRest, "Action recovers to updated directional rest")
		check(actor.set_locomotion(NorthWalk), "Admitted loop starts locomotion")
		actor.advance_visual(.2)
		check(actor.clip==NorthWalk and actor.texture.region==Rect2(NorthWalk.regions[1]), "Movement clock advances through authored stride")
		actor.set_locomotion(NorthWalk)
		actor.advance_visual(.2)
		check(actor.texture.region==Rect2(NorthWalk.regions[2]), "Repeated movement does not restart stride")
		check(actor.play_attack(1,ThrustClip), "Attack overrides walking")
		actor.set_locomotion(NorthWalk)
		check(actor.clip==ThrustClip, "Movement snapshots cannot interrupt attack")
		actor.advance_visual(.6)
		check(actor.clip==NorthWalk, "Attack returns to moving state when movement continues")
		actor.set_locomotion(null)
		check(actor.clip==NorthRest, "Stopping immediately restores directional rest")
		check(not actor.set_locomotion(ThrustClip), "One-shot cannot be used as locomotion")
		actor.free()
	print("Sprite clip: %s checks, %s failures"%[checks,failures])
	quit(1 if failures else 0)
