extends SceneTree
const South = preload("res://themes/minotaur_south_walk.tres")
const North = preload("res://themes/minotaur_north_walk.tres")
const Rest = preload("res://themes/minotaur_south_rest.tres")
const Attack = preload("res://themes/minotaur_south_attack.tres")
const Actor = preload("res://presentation/pixel_actor.gd")
func _initialize() -> void: _run.call_deferred()
func _run() -> void:
	for clip in [South, North]:
		assert(clip.validation_error().is_empty())
		assert(clip.looping)
		assert(clip.regions.size() == 4)
		assert(clip.frame_at(0.0) == clip.frame_at(0.64))
	var actor := Actor.new()
	root.add_child(actor)
	assert(actor.reset_playback(Rest))
	assert(actor.set_locomotion(South))
	actor.advance_visual(0.2)
	assert(actor.clip == South)
	assert(actor.play_attack(1, Attack))
	actor.advance_visual(0.7)
	assert(actor.clip == South)
	assert(actor.set_locomotion(null))
	assert(actor.clip == Rest)
	print("Minotaur walking: 15 checks passed")
	quit()
